[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "raggify",
    "raggify-client",
]

[tool.uv.sources]
raggify = { workspace = true }
raggify-client = { workspace = true }
